# Generated by Django 4.0.4 on 2022-05-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('rating', models.FloatField(verbose_name='rating')),
                ('numberOfVoters', models.IntegerField(verbose_name='numberOfVoters')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='username'),
        ),
    ]
